### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by 463010817** [samsha/svg2canvas#6]
在线演示上使用一个含有中文文字的svg，生成的canvas代码，中文是乱码的
![image](https://user-images.githubusercontent.com/18484424/134798094-208d0401-ce1f-4570-8e3d-5d59866b8457.png)

**Comment by LeoYawoo** [comment]
问题点在于浏览器自带的atob解析utf-8有问题,使用js-base64的Base64.decode替代就好了
参考:
https://github.com/dankogai/js-base64
